### ISSUE TITLE
Some Apps are listed as running that don't show up in meminfo, procstat nor ps

### ISSUE THREAD

**Issue by ronnac** [visnkmr/backgroundappslist#4]
This is a question, not a bug. 
The app shows me a list of running 3rd party apps, that seems to be correct, because each of the listed apps can be force closed manually. 
I am puzzled by the fact, however, that some of these apps don't figure in the results of any of these adb commands:
- adb shell ps
- adb shell dumpsys procstats --current
- adb shell dumpsys meminfo

It seems like these apps are considered as "running", while they have no process associated and no memory footprint. Am I getting this right?
In what kind of state are these apps?
Is there an adb command that produces the same output as backgroundsapplist?
One example is Davx5.

**Comment by ronnac** [comment]
Thanks you for your quick reply. Yes, the app is intensely useful. Yes, Davx5 performs periodic syncs. Is there a way to identify such apps via ADB?

**Comment by visnkmr** [comment]
Hey, 
You can find apps and their service that are started on boot using the adb command
adb shell dumpsys package resolvers receiver | awk '/android.intent.action.BOOT_COMPLETED/{p=1;next}/:/{p=0}p {print $2}'

**Comment by ronnac** [comment]
This put me on the right track. I finally used this:
adb shell dumpsys alarm | grep -o "Alarm{.*}" | cut -d " " -f6 | cut -d "}" -f1 |sort| uniq

**Comment by visnkmr** [comment]
Glad to be of help.
