### ISSUE TITLE
Update on Goggle playstore

### ISSUE THREAD

**Issue by Arthur1967** [visnkmr/backgroundappslist#405]
It says I need to update the app but when I go to the play store there is no update Google play store. I mean I'm using an android box. Thank you.

**Comment by visnkmr** [comment]
Hey, Thanks for reporting.
The updated version is already available on github, it has been sent for review to Google Play and Amazon Appstore today. The appstore updates should arrive in a day, the github version is already available here. Sometimes appstores do take some time to roll out updates based on region, I'll look into what can be done to prevent these in the future.
Latest version on:

Fire TV, Tablet appstore is 1.3A13I,
Google play version is 1.3G12I.

**Comment by Arthur1967** [comment]
OK thank you

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.

**Comment by Arthur1967** [comment]
No, I just forgot to close it. Sorry.
