### ISSUE TITLE
Update app for FireTV

### ISSUE THREAD

**Issue by sremuuhh23** [visnkmr/backgroundappslist#417]
![image](https://github.com/visnkmr/backgroundappslist/assets/123305013/4dbdcb4a-6024-4c6c-bfd1-38bd84767eea)

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by MKentV** [comment]
Please update the app

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
