### ISSUE TITLE
Update 1.3A12I

### ISSUE THREAD

**Issue by SeanDSB** [visnkmr/backgroundappslist#430]
Hello to whom this may concern! It has taken me a while just to find any avenue to write this very message!

Which there is no help in understanding how to contact a person on Github my means if messaging!

Please update the following Background APP on the Amazon Fire For version 1.3A12I.

This message is being written on 28 October! Thank you!

**Comment by connect2400** [comment]
I, too, had to go thru several hoops to get here, out of a respect for a developer's embedded request: v1.3G11i requests update for Amazon, but I did not download it there. Just FYI. Let me know if any questions.

**Comment by visnkmr** [comment]
> I, too, had to go thru several hoops to get here, out of a respect for a developer's embedded request: v1.3G11i requests update for Amazon, but I did not download it there. Just FYI.
> 
> Clicking the Update App button below that message took my browser to 404; I reviewed the URL and found my way to the app's Google Play page and updated successfully.
> 
> Let me know if any questions.

Thanks for letting me know about this. I must have forgotten to update the text when i simulatneously rolled out updates to Google Play and amazon appstore. Will fix it in the next release.

**Comment by visnkmr** [comment]
> Hello to whom this may concern! It has taken me a while just to find any avenue to write this very message!
> 
> Which there is no help in understanding how to contact a person on Github my means if messaging!
> 
> Please update the following Background APP on the Amazon Fire For version 1.3A12I.
> 
> This message is being written on 28 October! Thank you!

If the issue is still present, please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6
