### ISSUE TITLE
Release Latest Update Asap!!! 

### ISSUE THREAD

**Issue by ItzWarLockOp** [visnkmr/backgroundappslist#458]
Please release the latest update of the app on Amazon App Store.
![IMG_20231104_150550](https://github.com/visnkmr/backgroundappslist/assets/98949064/e4f6df49-f73b-4053-af02-7d2b4dcf45b6)

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6
