### ISSUE TITLE
The background app on firestick needs an update 

### ISSUE THREAD

**Issue by MartinAD91** [visnkmr/backgroundappslist#478]
![20231119_113952.jpg](https://github.com/visnkmr/backgroundappslist/assets/151403159/cef83aa4-56bc-4a8a-b7b3-ac69fa8e1c4d)

**Comment by visnkmr** [comment]
It should already be available from the appstore.
- If not please uninstall, reboot the device, and then reinstall the app,
- If this doesn't work you have two options,
  - one, wait for the updates to be available for your region, else
  - two, download the apk already available on github (https://visnkmr.github.io/appstore).
  - Transfer it to fire stick using wireless file manager and install.
  
Assumptions:
- You know how to update a fire tv app from the appstore.
- You are using a fire tv
- You installed the app from github/amazon appstore.
If any of the assumptions are wrong, do tell me.

Existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6
