### ISSUE TITLE
Your device time is incorrect?!

### ISSUE THREAD

**Issue by develcore** [visnkmr/backgroundappslist#5]
When starting the app, the following error appears:

`[…]
Your device time is incorrect
If your device time is correct.
It seems we have forgotten the app.
[…]`

The app cannot be used. According to the App Store, it is also the latest version. 

The error is since today. Until yesterday everything worked fine.

App version: 1.302A6i
Hardware: FireTV Stick (3rd gen)
OS: Fire OS 7.6.1.4 (PS7614/3227)
Date: January 22, 2023
Time: 03:44 AM
Time zone: Berlin (GMT+1)

![844E24CB-F674-4A33-8C7C-B52EDB551A90](https://user-images.githubusercontent.com/60314110/213898345-2c0fea62-10f7-4e71-99a7-d83de3916f13.jpeg)

**Comment by MiahFuta** [comment]
Same issue, please fix!

**Comment by Sacohen9665** [comment]
Having the same issue.
It started today 1/22/23. 
Everything was working fine yesterday.
I uninstalled the app and reinstalled it from the Amazon App Store which SHOULD be the latest version and I’m getting the same error message.
Please fix soon! 🙏🏻

**Comment by spamhater-grav** [comment]
Also having issues with the date and the expiry of the app. This is one of my favorite maintenance tools as well - Fire Cube2nd Gen

Loving your work !

**Comment by com657** [comment]
same issue  with time

**Comment by Endohzilla** [comment]
Same here. Always use this app so please fix ASAP thanks

**Comment by alysynn** [comment]
me too!

App version: 1.302A6i
Hardware: FireTV Stick (3rd Gen)
OS: Fire OS 7.6.1.4 (PS7614/3227)
Date: January 22, 2023
Time: 11:53:20 AM
Time zone: Michigan (MI (GMT-5)

**Comment by rogermae** [comment]
Same here
App version: 1.302A6i
Hardware: FireTV Stick 4k Max 
OS: Fire OS 7.6.1.4 (PS7614/3227)
Date: January 22, 2023
Time: 12:08:03 PM
Time zone: Maryland (New York GMT-05:00)

**Comment by passaic13** [comment]
I am getting the same message as written above about the version and time and to contact you.
Please advise. Thank you

**Comment by Grovedrovej** [comment]
Getting same message! Please fix and update

**Comment by itsBillyBob** [comment]
Same problem started today (01/22/2023). Please prioritize.

**Comment by denzel781** [comment]
Same problem  started today

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue. 
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://t.me/vishnunkmr) and here once its live.

**Comment by denzel781** [comment]
Visnkmr/Backgroundappslistm. Thanks

**Comment by alysynn** [comment]
Very much appreciated- ty!On Jan 23, 2023, at 12:49 AM, Vishnu N K ***@***.***> wrote:﻿
Hey,
Thanks for reporting the issue.
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on our telegram channel and here once its live.

**Comment by denzel781** [comment]
Great, thanks for the update!

**Comment by Sacohen9665** [comment]
Thanks for the fix.
I love the app and use it all the time.

**Comment by rogermae** [comment]
Thanks, working.

**Comment by visnkmr** [comment]
The latest update should have fixed the issue. Else feel free to reopen the thread.

**Comment by denzel781** [comment]
Awesome, thanks!
