### ISSUE TITLE
Background App needs updated on FireTV cube

### ISSUE THREAD

**Issue by sremuuhh23** [visnkmr/backgroundappslist#6]
![550A5247-1D8A-4478-A3CF-361DE20CA19F](https://user-images.githubusercontent.com/123305013/213916648-52a088db-6360-4e67-9df8-5b7ddc076740.jpeg)

received this message when I went to use the app. It says I am seeing the message because my device time is correct and it seems that you have forgotten about the app.  To please remind you to update the app via telegram but there is no option to message you on telegram.

**Comment by Endohzilla** [comment]
I get this too. Please fix

**Comment by Grovedrovej** [comment]
Same with me as well! Please update

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue. 
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://t.me/vishnunkmr) and here once its live.

**Comment by visnkmr** [comment]
The latest update should have fixed the issue. Else feel free to reopen the thread.
