### ISSUE TITLE
New version it says to remind you to update it on the App Store Google play thank you

### ISSUE THREAD

**Issue by Arthur1967** [visnkmr/backgroundappslist#669]

**Comment by jeyjai** [comment]
@visnkmr 
It mentiones you forgot the amazon appstore app, but the latest version on github is 1.3A14i, and on google play its still on 1.3G13i, so please update that one as well

**Comment by visnkmr** [comment]
Hey, just got the notification of these messages today. First of all Thanks for reminding me, the update should already be available on github or our [appstore](https://visnkmr.github.io/appstore); the update has also been submitted to amazon appstore and google play which will be available after their usual review.

**Comment by Arthur1967** [comment]
Thank you I've been waiting for the update. Have a good day.
