### ISSUE TITLE
Google Play Store

### ISSUE THREAD

**Issue by Anji33017** [visnkmr/backgroundappslist#672]
When I click on "open app in app store", I get the Google Play Store logo, but then it transitions into a blank page with this popup: To view this content, install and setup a web browsing app. Also, if I go to the Google Play Store directly, it lists the last update as January 23, 2024.

**Comment by visnkmr** [comment]
Hey, just got the notification of these messages today. First of all Thanks for reminding me, the update should already be available on github or our [appstore](https://visnkmr.github.io/appstore); the update has also been submitted to amazon appstore and google play which will be available after their usual review.
