### ISSUE TITLE
You forgot to update google play app

### ISSUE THREAD

**Issue by jeyjai** [visnkmr/backgroundappslist#675]
the google play app is saying you forgot the "amazon appstore app", but the latest version on github is 1.3A14i, and on google play its still on 1.3G13i, so please update the google play version as well so we get rid of this notification
@visnkmr

**Comment by visnkmr** [comment]
Thanks for reminding me, just got the notification on github app, the update should already be available on github; the update has also been submitted to amazon appstore and google play which will be available after their usual review.

**Comment by jeyjai** [comment]
@visnkmr hey, how long does is usually take for google updates to be approved? Its basically been 4 weeks now and still no update.

And just an idea for you, why dont you make it possible to close/hide the "remind me" message in future versions. Being forced to have it on screen, especially on the tv version, is really annoying.
Just make it so the ok button returns the app to its normal layout and maybe include a checkbox to permanently hide it till the next version

**Comment by visnkmr** [comment]
Usually it takes anywhere between a few hours to a month in the worst case. Anyway the new version should already be available on our [appstore](https://visnkmr.github.io/appstore) if you prefer that way.

**Comment by jeyjai** [comment]
@visnkmr sorry but it's almost been 2 months now since you said you sent google an update and it still haven't been updated, it's still on the update from january, 1.3G13i

I'm not able to use other stores or sideload apks on one of my devices so I'm pretty much stuck with this one till it gets updated.
Could you contact google and make sure they got the update and are working on it?

**Comment by visnkmr** [comment]
Please refer https://github.com/visnkmr/visnkmr/issues/40

**Comment by jeyjai** [comment]
> Please refer [visnkmr/visnkmr#40](https://github.com/visnkmr/visnkmr/issues/40)

Not sure how that is gonna help in any way, google play store is still on 1.3G13i.
Literally takes you 2 seconds to verify for yourself
https://play.google.com/store/apps/details?id=io.github.visnkmr.bapl
I just grabbed this screenshot
![Screenshot_20240709_122135_Brave](https://github.com/visnkmr/backgroundappslist/assets/7854537/bcf83e66-2a17-4808-8c62-6af053f5ab0d)


It's almost been 3 months since you said you sent google your update, other apps can update in a few days ago it's pretty obvious that you either didn't send them the update or something went wrong and you have to contact them again for it to actually be updated on google.
