### ISSUE TITLE
Device time incorrect

### ISSUE THREAD

**Issue by songirlaji** [visnkmr/backgroundappslist#7]
I am also experiencing this same problem.  When will this be resolved?

**Comment by capercameback** [comment]
Same issue V 1.302A6i
Please update the app if you can.

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue. 
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://t.me/vishnunkmr) and here once its live.

**Comment by visnkmr** [comment]
The latest update should have fixed the issue. Else feel free to reopen the thread.
