### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by cris10an** [visnkmr/backgroundappslist#713]
Google play, (android tv) gives me version 1.3G13i(38) trying upgrade via sideload to 1.3A15i(25) gives me: 
App installation failed, the new package has an older version code then the currently installed package

Fresh sideloading of 1.3A15i(25) ends with automatic 'upgrade' to 1.3G13i(38) from Google play

**Comment by visnkmr** [comment]
Ohk, thanks for notifying me regarding this will update the version number to prevent this tomorrow. Thanks for the breakdown and steps to reproduce the issue.

**Comment by 1mediamaster** [comment]
That's what I've been experiencing for 3 weeks +-
Perfect explanation

**Comment by 1mediamaster** [comment]
> Google play, (android tv) gives me version 1.3G13i(38) trying upgrade via sideload to 1.3A15i(25) gives me: App installation failed, the new package has an older version code then the currently installed package
> 
> Fresh sideloading of 1.3A15i(25) ends with automatic 'upgrade' to 1.3G13i(38) from Google play

Do you see a recent problem??
