### ISSUE TITLE
Fix java.lang.RuntimeException: Failed to initialize display event receiver.  status=-19 in io.github.visnkmr.bapl.MainActivity.S

### ISSUE THREAD

**Issue by visnkmr** [visnkmr/backgroundappslist#720]
### Stacktrace ###

io.github.visnkmr.bapl.MainActivity.S;

io.github.visnkmr.bapl.MainActivity.d;

io.github.visnkmr.bapl.MainActivity$x0.onPreExecute;

io.github.visnkmr.bapl.MainActivity.f;

io.github.visnkmr.bapl.MainActivity.onCreate;

### Reason ###

java.lang.RuntimeException: Failed to initialize display event receiver.  status=-19

### Link to App Center ###

* [https://appcenter.ms/users/visnkmr/apps/Background-Apps-List/crashes/errors/900402163u](https://appcenter.ms/users/visnkmr/apps/Background-Apps-List/crashes/errors/900402163u)

**Comment by quibbler01** [comment]
Have you solve this problem?
