### ISSUE TITLE
FireTV Cube app issue

### ISSUE THREAD

**Issue by sremuuhh23** [visnkmr/backgroundappslist#79]
After force closing all my open apps, all 230+ system apps appear. Just started doing this Saturday 5/6/23![image](https://user-images.githubusercontent.com/123305013/236712816-e8fd6230-9ff5-4e40-8877-8199f57bffe6.jpeg)

**Comment by sremuuhh23** [comment]
Thank you for replying.  I do not think shoeing all the system apps after is necessary.  A lot of the shown system apps cannot be closed and the fact that there are 230 of them makes it’s pointless.  Just my two cents.  Leave it the way it used to be.  Thank you. On May 8, 2023, at 5:35 PM, Vishnu N K ***@***.***> wrote:﻿
Hey,
Starting in the latest version, the app now shows system apps running in background once all user apps are closed.  So if this was shown after you closed all user apps using close all apps button, then it is desired behaviour, I hope it was useful. If its not, please don't hesitate to tell us, based on user feedback we will roll it back to previous version if its what you wish to use.

**Comment by visnkmr** [comment]
Yeah based on feedback recieved in the [github discussion here](https://github.com/visnkmr/backgroundappslist/discussions/81) we decided to swtch to the old way with optional button to switch to system apps list.

**Comment by sremuuhh23** [comment]
Hello. The app still will not update on Amazon AppStore. I've uninstalled and reinstalled and it still shows the message about updating.
