### ISSUE TITLE
Firestick app store is complaining

### ISSUE THREAD

**Issue by capercameback** [visnkmr/backgroundappslist#8]
V 1.302A6i
Please update the app if you can.

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue. 
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://t.me/vishnunkmr) once its live.

**Comment by capercameback** [comment]
Done, had to uninstall/reinstall. Working as expected....THANK YOU!

**Comment by visnkmr** [comment]
The latest update should have fixed the issue. Else feel free to reopen the thread.
