### ISSUE TITLE
file explorer

### ISSUE THREAD

**Issue by lelas31450** [visnkmr/backgroundappslist#859]
1.7A3i on Android 14 phone
At launch  State there is a New version
Update button don't give Access to New version
Regards,
lelas31450@gmail.com

**Comment by visnkmr** [comment]
The latest version of the app is available on our [appstore](https://visnkmr.github.io/appstore). Regarding, the Google Play Store version, the update was rejected by Google play stating some compliance related policy issues relating to app icon sizes for Android TV. The exact issue we are facing is mentioned [here](https://support.google.com/googleplay/android-developer/thread/270001289/android-tv-app-rejected-with-reason-no-full-size-app-banner-and-or-icon?hl=en). If you have any sort of contact with someone who works on Google's play store related teams do let me know. Until then I will try to publish the update from time to time hoping for a better reviewer.

Please refer https://github.com/visnkmr/visnkmr/issues/40
