### ISSUE TITLE
Receiving device time incorrect error

### ISSUE THREAD

**Issue by stenve** [visnkmr/backgroundappslist#9]
Receiving the error:
 - your device time is incorrect

App version: 1.302A6i
Product: Amazon Firestick 4k Max

I have checked the device time multiple times and it is correct. I have also uninstalled and reinstalled Background APL and still receive the same error.

The app worked fine Jan 21 in the afternoon and stopped working Jan 22. 

I hope this information helps to resolve the issue because it is quite handy.

Thanks.

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue. 
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://t.me/vishnunkmr) once its live.

**Comment by visnkmr** [comment]
The latest update should have fixed the issue. Else feel free to reopen the thread.
